# Generated by Django 5.1.4 on 2024-12-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pethaven', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='adoption_fee',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='composition',
            new_name='health_issue',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prodapp',
            new_name='origin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='product',
            name='breed',
            field=models.CharField(default='', max_length=100),
        ),
    ]
