# Generated by Django 5.1.4 on 2024-12-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pethaven', '0002_rename_discounted_price_product_adoption_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C', 'Cat'), ('D', 'Dog'), ('B', 'Bird'), ('O', 'Other')], max_length=2),
        ),
    ]
