# Generated by Django 5.1.4 on 2024-12-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pethaven', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='district',
            new_name='division',
        ),
    ]
