# Generated by Django 5.1.4 on 2024-12-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pethaven', '0005_rename_district_customer_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
